Update SDK.yaml

diff --git a/.github/workflows/SDK.yaml b/.github/workflows/SDK.yaml
--- a/.github/workflows/SDK.yaml
+++ b/.github/workflows/SDK.yaml
@@ -45,7 +45,7 @@ jobs:
       run:
         shell: bash
     steps:
-    - name: Checkout YAAWG repository
+    - name: Checkout AWG repository
       uses: actions/checkout@v5
       with:
         path: amneziawg
@@ -99,6 +99,33 @@ jobs:
         echo "CONFIG_PACKAGE_luci-proto-amneziawg=y" >> openwrt/.config
         ./openwrt/scripts/feeds install -a
         make -C openwrt defconfig
+
+    - name: Update PKG_SOURCE_VERSION & HASH
+      run: |
+        set -e -x
+        cd openwrt/package
+        update_pkg() {
+          local pkg_dir="$1"
+          local repo="$2"
+          local branch="$3"
+          echo "--- Updating $pkg_dir from $branch ---"
+          commit=$(git ls-remote "$repo" "$branch" | awk '{print $1; exit}')
+          url="$repo/archive/$commit.tar.gz"
+          hash=$(curl -L --retry 3 -s "$url" | sha256sum | cut -d' ' -f1)
+          if [ -d "$pkg_dir" ]; then
+            cd "$pkg_dir"
+            sed -i "s/^PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=$commit/" Makefile
+            sed -i "s/^PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=$hash/" Makefile
+            cd - >/dev/null
+            echo "--- $pkg_dir updated: $commit ---"
+          else
+            echo "Warning: directory $pkg_dir not found"
+          fi
+        }
+        update_pkg "kmod-amneziawg" "https://github.com/amnezia-vpn/amneziawg-linux-kernel-module.git" "feature/awg2"
+        update_pkg "amneziawg-tools" "https://github.com/amnezia-vpn/amneziawg-tools.git" "master"
+        cd - >/dev/null
+
   
     - name: Compile AmneziaWG packages
       run: |
